import {
  darkGray,
  black,
  white80,
  white40,
  goodweebsPurple,
  white10,
  white95,
  white15,
  white12_5,
  alienGreen,
} from "yep/colors";

export const darkTheme = {
  background: black,
  navBackground: darkGray,
  button: white12_5,
  text: white95,
  subText: white80,
  textInverted: black,
  iconFill: white95,
  footnote: white80,
  chipBorder: white15,
  selectedChipFill: white95,
  listCount: white80,
  accent: goodweebsPurple,
  listItemBackground: white10,
  inputPlaceholder: white40,
  success: alienGreen,
};
