fragment MediaPosterFragment on Media {
  id
  title {
    romaji
    native
    english
  }
  coverImage {
    large
    medium
  }
}

fragment AnimeListEntryFragment on Media {
  id
  type
  title {
    romaji
    native
    english
  }
  coverImage {
    large
    medium
  }
  episodes
  chapters
  volumes
  status
  startDate {
    year
    month
    day
  }
  endDate {
    year
    month
    day
  }
  nextAiringEpisode {
    id
    airingAt
    episode
  }
  mediaListEntry {
    id
    progress
    progressVolumes
    status
    score
  }
}

fragment AnimeRelationFragment on Media {
  id
  isFavourite
  title {
    romaji
    native
    english
  }
  type
  format
  coverImage {
    large
    medium
    color
  }
}

fragment MediaExternalLinkData on MediaExternalLink {
  id
  url
  site
}

fragment MediaTrailerData on MediaTrailer {
  id
  thumbnail
  site
}

fragment AnimeFragment on Media {
  id
  type
  title {
    romaji
    native
    english
  }
  startDate {
    year
    month
    day
  }
  endDate {
    year
    month
    day
  }
  status
  genres
  episodes
  chapters
  volumes
  description
  isFavourite
  studios(isMain: true) {
    nodes {
      id
      name
    }
  }
  averageScore
  coverImage {
    large
    medium
    color
  }
  trailer {
    ...MediaTrailerData
  }
  externalLinks {
    ...MediaExternalLinkData
  }
  nextAiringEpisode {
    id
    airingAt
    episode
  }
  mediaListEntry {
    id
    progress
    progressVolumes
    status
    score
  }
  relations {
    edges {
      id
      relationType
      node {
        ...AnimeRelationFragment
      }
    }
  }
  characters {
    nodes {
      ...CharacterListItemData
    }
  }
}
