query GetNotifications($page: Int, $perPage: Int, $reset: Boolean) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      total
      hasNextPage
    }
    notifications(
      type_in: [AIRING, RELATED_MEDIA_ADDITION]
      resetNotificationCount: $reset
    ) {
      ... on AiringNotification {
        id
        episode
        contexts
        createdAt
        media {
          id
          type
          title {
            romaji
            native
            english
          }
          coverImage {
            medium
            large
          }
        }
      }
      ... on RelatedMediaAdditionNotification {
        id
        context
        createdAt
        media {
          id
          type
          title {
            romaji
            native
            english
          }
          coverImage {
            medium
            large
          }
        }
      }
    }
  }
}
