import {
  darkGray,
  black,
  white80,
  white40,
  goodweebsPurple,
  white10,
  white20,
  white95,
  white15,
  white12_5,
  alienGreen,
  darkBlue,
  white,
  gray6,
  white30,
  white60,
} from "yep/colors";

export const darkTheme = {
  background: black,
  navBackground: darkGray,
  button: white12_5,
  buttonBorder: white30,
  text: white95,
  subText: white80,
  subHeader: white60,
  textInverted: black,
  iconFill: white95,
  footnote: white80,
  chipBorder: white15,
  selectedChipFill: white95,
  listCount: white80,
  accent: goodweebsPurple,
  listItemBackground: white10,
  listItemBorder: white20,
  inputPlaceholder: white40,
  success: alienGreen,
};

export const websiteTheme = {
  navBackground: darkBlue,
  text: white,
  subText: white95,
  hoveredLink: goodweebsPurple,
  downloadSectionBackground: goodweebsPurple,
  pageBackground: gray6,
};
